# Site settings
title: Black Matter
email: george.rafael@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Rambling about web development in particular, programming in general, philosophy on 
  the side and everything else in the middle.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cored.github.io" # the base hostname & protocol for your site
twitter_username: cor3d
github_username:  cored
permalink: /blog/:year/:month/:day/:title
pagination: 5

# Build settings
markdown: redcarpet

# Syntax 
highlighter: pygments
